final: student_detail.o stud_add.o stud_del.o stud_mod.o rev_print.o stud_save.o stud_show.o stud_sort.o
	cc student_detail.c stud_add.c stud_del.c stud_mod.c rev_print.c stud_save.c stud_show.c stud_sort.c -o final
student_detail.o:student_detail.c
	cc -c student_detail.c
stud_add.o: stud_add.c
	cc -c stud_add.c
stud_del.o:stud_del.c
	cc -c stud_del.c
stud_mod.o:stud_mod.c
	cc -c stud_mod.c
rev_print.o:rev_print.c
	cc -c rev_print.c
stud_save.o:stud_save.c
	cc -c stud_save.c
stud_show.o:stud_show.c
	cc -c stud_show.c
stud_sort.o:stud_sort.c
	cc -c stud_sort.c
