final: main.o book_add.o book_del.o issue_book.o book_save.o book_view.o return_book.o upt_book.o user_add.o
	cc main.o book_add.o book_del.o issue_book.o book_save.o book_view.o return_book.o upt_book.o user_add.o -o final
main.o:main.c
	cc -c main.c
book_add.o: book_add.c
	cc -c book_add.c
book_del.o:book_del.c
	cc -c book_del.c
issue_book.o:issue_book.c
	cc -c issue_book.c
book_save.o:book_save.c
	cc -c book_save.c
book_view.o:book_view.c
	cc -c book_view.c
return_book.o:return_book.c
	cc -c return_book.c
upt_book.o:upt_book.c
	cc -c upt_book.c
user_add.o:user_add.c
	cc -c user_add.c
